@echo off
cd /d "C:\Users\HP PAVILION\app_areas_verdes"
echo Compilando Areas Verdes Donihue...
C:\src\flutter\bin\flutter.bat build web --release
echo Abriendo en Chrome...
start chrome "C:\Users\HP PAVILION\app_areas_verdes\build\web\index.html"
